# Generated by Django 2.2.1 on 2019-08-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirm',
            name='saet',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
